### ISSUE TITLE
Template Creation for the exercises

### ISSUE THREAD

**Issue by pankhurivanjani** [TheRoboticsClub/colab-gsoc2020-Shreyas_Gokhale#13]
Please share the link to main script which needs to be modified for you creating a new exercise

**Comment by shreyasgokhale** [comment]
[Exercise Script](https://github.com/JdeRobot/CustomRobots/blob/foxy-devel/amazon_robot/exercise/single_robot.py)
[Launch Script](https://github.com/JdeRobot/CustomRobots/blob/foxy-devel/amazon_robot/amazon_robot_bringup/bringup/launch/amazon_robot_in_aws_world.py)
